name: Fallback Workflow

on:
  schedule:
    - cron: "45 7 * * *" # Runs every Sunday at 7:45 AM (15 minutes after the main workflow)
  workflow_dispatch: # Allows manual trigger

jobs:
  fallback-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set the GH_TOKEN environment variable

    steps:
      - name: Check if Main Workflow has been triggered in the past hour
        id: check_main_workflow
        run: |
          # Get the current time and time one hour ago in ISO format
          now=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          one_hour_ago=$(date --utc --date='1 hour ago' +%Y-%m-%dT%H:%M:%SZ)

          echo "Current time: $now"
          echo "Time one hour ago: $one_hour_ago"

          # GitHub API request to get the last run of the main workflow
          last_run_created_at=$(gh api repos/${{ github.repository }}/actions/workflows/nodejs.yml/runs \
            --jq '.workflow_runs[0].created_at')

          echo "Last run created at: $last_run_created_at"

          # Compare the last run time to one hour ago
          if [[ "$last_run_created_at" > "$one_hour_ago" && "$last_run_created_at" < "$now" ]]; then
            echo "last_run=recent" >> $GITHUB_ENV
            exit 0
          else
            echo "last_run=not_recent" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        if: ${{ env.last_run == 'not_recent' }}
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: ${{ env.last_run == 'not_recent' }}
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        if: ${{ env.last_run == 'not_recent' }}
        run: npm install

      - name: Run Puppeteer script
        if: ${{ env.last_run == 'not_recent' }}
        env:
          DNI: ${{ secrets.DNI }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node register.js
